[package]
name = "vvm"
version = "0.1.0"
edition = "2021"

[dependencies]
bounded-vec-deque = "0.1.1"
clap = "3.0.0-beta.5" # A simple to use, efficient, and full-featured Command Line Argument Parser
